templates:
	xelatex -shell-escape templates
	xelatex -shell-escape templates

clean:
	rm -rf _minted-templates *.aux *.log *.out *.toc *.synctex.gz *.bbl *.blg *.bcf *.xml *.fls *.fdb_latexmk *.synctex\(busy\) *.pdf
